# Generated by Django 2.2.7 on 2019-11-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaHost', models.CharField(max_length=100)),
                ('verticalHost', models.CharField(max_length=100)),
                ('segmentoHost', models.CharField(max_length=100)),
                ('produtoHost', models.CharField(max_length=100)),
                ('filialHost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tickethost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=100)),
            ],
        ),
    ]
